#!/bin/bash

#SBATCH -N 1
#SBATCH -c 1

#SBATCH --gres=gpu
#SBATCH -p res-gpu-small
#SBATCH --qos=short
#SBATCH -t 48:00:00

#SBATCH --job-name=pGNNC80
#SBATCH --mail-type=ALL
##SBATCH --mail-user slxb76@durham.ac.uk

source /etc/profile
python main.py
